const v1Router = require('express').Router()

const authRouter = require('./auth-router')
const cardRouter = require('./card-router')
const setRouter = require('./set-router')
const cardV2Router = require('./card-v2-router')
const setV2Router = require('./set-v2-router')
const collectedCardRouter = require('./collected-card-router')
const collectedProductRouter = require('./collected-product-router')
const transactionRouter = require('./transaction-router')
const productRouter = require('./product-router')
const marketPricesRouter = require('./market-prices-router')
const referenceDataRouter = require('./reference-data-router')
const saleRouter = require('./sale-router')
const portfolioRouter = require('./portfolio-router')
const typeRouter = require('./type-router')
const rarityRouter = require('./rarity-router')
const printingRouter = require('./printing-router')
const bulkSplitRouter = require('./bulk-split-router')
const sortingRouter = require('./sorting-router'
)

v1Router.use('/auth', authRouter)
v1Router.use('/sets', setRouter)
v1Router.use('/cards', cardRouter)
v1Router.use('/sets-v2', setV2Router)
v1Router.use('/cards-v2', cardV2Router)
v1Router.use('/collected-cards', collectedCardRouter)
v1Router.use('/collected-products', collectedProductRouter)
v1Router.use('/transactions', transactionRouter)
v1Router.use('/products', productRouter)
v1Router.use('/market-prices', marketPricesRouter)
v1Router.use('/reference-data', referenceDataRouter)
v1Router.use('/sales', saleRouter)
v1Router.use('/portfolio', portfolioRouter)
v1Router.use('/types', typeRouter)
v1Router.use('/rarities', rarityRouter)
v1Router.use('/printings', printingRouter)
v1Router.use('/bulk-splits', bulkSplitRouter)
v1Router.use('/sortings', sortingRouter)

module.exports = v1Router
